# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /tmp/download
    state: directory
    mode: '0755'

# https://stackoverflow.com/questions/24861311/forwarding-port-80-to-8080-using-nginx
- name: Install nginx config
  template:
    src: ./templates/wildfly.conf
    dest: "/etc/nginx/conf.d/wildlife.conf"

